apiVersion: v1
kind: Service
metadata:
  name: sv-region-api
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 8080
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: sv-contact-api
spec:
  type: NodePort
  selector:
    app: my-contact-api
  ports:
  - protocol: TCP
    port: 4040
    targetPort: 8080
    nodePort: 30071
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq-app
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
    nodePort: 30070
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ui
spec:
  type: NodePort
  selector:
    app: rabbitmq-app
  ports:
  - protocol: TCP
    port: 15672
    targetPort: 15672
    nodePort: 30060
---
apiVersion: v1
kind: Service
metadata:
  name: sv-prometheus
spec:
  type: NodePort
  selector:
    app: prometheus-app
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30050
---
apiVersion: v1
kind: Service
metadata:
  name: sv-grafana
spec:
  type: NodePort
  selector:
    app: grafana-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30030