apiVersion: v1
kind: Service
metadata:
  name: sv-region-api
spec:
  type: NodePort
  selector:
    app: regionservice
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 8080
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: sv-contact-api
spec:
  type: NodePort
  selector:
    app: contactservice
  ports:
  - protocol: TCP
    port: 4040
    targetPort: 8080
    nodePort: 30071
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq-app
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30070
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: 15692
      nodePort: 30093
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ui
spec:
  type: NodePort
  selector:
    app: rabbitmq-app
  ports:
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30060
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: 15692
      nodePort: 30092

---
apiVersion: v1
kind: Service
metadata:
  name: sv-prometheus
spec:
  type: NodePort
  selector:
    app: prometheus-app
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30050
---
apiVersion: v1
kind: Service
metadata:
  name: sv-grafana
spec:
  type: NodePort
  selector:
    app: grafana-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30030

---

  apiVersion: v1
  kind: Service
  metadata:
    name: sqlserver
  spec:
    type: NodePort
    selector:
      app: sqlserver
    ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31433
---

apiVersion: v1
kind: Service
metadata:
  name: sv-redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30377
