##volumes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: docker-sc
provisioner: docker.io/hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  storageClassName: docker-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/valmi/TC-Data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  storageClassName: docker-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
spec:
  storageClassName: docker-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---

# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: region-secret
type: Opaque
data:
  ConnectionStrings__Database: U2VydmVyPXNxbHNlcnZlciwxNDMzO0RhdGFiYXNlPXRlY2hjaGFsbGVuZ2VyZWdpb247VXNlciBJZD1zYTtQYXNzd29yZD1Zb3VyU3Ryb25nIVBhc3N3MHJkO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz1GYWxzZTtFbmNyeXB0PVRydWU7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs=
  MassTransit__User: Z3Vlc3Q=
  MassTransit__Password: Z3Vlc3Q=
---

apiVersion: v1
kind: Secret
metadata:
  name: contact-secret
type: Opaque
data:
  ConnectionStrings__Database: U2VydmVyPXNxbHNlcnZlciwxNDMzO0RhdGFiYXNlPXRlY2hjaGFsbGVuZ2Vjb250YWN0O1VzZXIgSWQ9c2E7UGFzc3dvcmQ9WW91clN0cm9uZyFQYXNzdzByZDtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTtDb25uZWN0aW9uIFRpbWVvdXQ9MzA7
  MassTransit__User: Z3Vlc3Q=
  MassTransit__Password: Z3Vlc3Q=
---

# configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "fiap-prometheus-metrics-regions"
        metrics_path: /metrics
        static_configs:
          - targets: ["sv-region-api:5050"]
      - job_name: "fiap-prometheus-metrics-contacts"
        metrics_path: /metrics
        static_configs:
          - targets: ["sv-contact-api:4040"]
      - job_name: "fiap-prometheus-metrics-rabbitmq"
        metrics_path: /metrics
        static_configs:
          - targets: ["rabbitmq-service:15692"]
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-config
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
      - name: prometheus-metrics
      editable: true
      type: prometheus
      access: proxy
      url: sv-prometheus:9090
      isDefault: true
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: regionconsumer-env-config
data:
  MassTransit__QueueCreateRegion: region-insert-queue
  MassTransit__Server: rabbitmq-service
  ConnectionStrings__Cache: sv-redis:6379
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: contactconsumer-env-config
data:
  MassTransit__QueueCreateRegion: contact-insert-queue
  MassTransit__Server: rabbitmq-service
  ConnectionStrings__Cache: sv-redis:6379
  Integrations__RegionApiUrl: http://sv-region-api:5050/api
  MESSAGE: "Mensagem do ConfigMap!"
---

# Deployments and Services for Tech Challenge Phase 4

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  annotations:
    description: "Deployment para SQL Server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "YourStrong!Passw0rd"
        - name: MSSQL_PID
          value: "Express"
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: sqlserver-data
          mountPath: /var/opt/mssql
      volumes:
      - name: sqlserver-data
        persistentVolumeClaim:
          claimName: sqlserver-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regionservice
  annotations:
    description: "Region Service"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regionservice
  template:
    metadata:
      labels:
        app: regionservice
    spec:
      containers:
      - name: regionservice
        image: vmrsilva/techchallange-fase4-region
        envFrom:
          - configMapRef:
              name: regionconsumer-env-config
          - secretRef:
              name: region-secret
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;']


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactservice
  annotations:
    description: "Contact Service"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contactservice
  template:
    metadata:
      labels:
        app: contactservice
    spec:
      containers:
      - name: contactservice
        image: vmrsilva/techchallange-fase4-contact:latest
        envFrom:
          - configMapRef:
              name: contactconsumer-env-config
          - secretRef:
              name: contact-secret
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;']




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regionconsumer
  annotations:
    description: "Deployment for consumer region"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regionconsumer
  template:
    metadata:
      labels:
        app: regionconsumer
    spec:
      containers:
      - name: regionconsumer
        image: vmrsilva/techchallange-fase4-region-consumer
        envFrom:
            - configMapRef:
                name: regionconsumer-env-config
            - secretRef:
                name: region-secret
        ports:
        - containerPort: 5050
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "100Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactconsumer
  annotations:
    description: "Deployment for consumer contacts"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactconsumer
  template:
    metadata:
      labels:
        app: contactconsumer
    spec:
      containers:
      - name: contactconsumer
        image: vmrsilva/techchallange-fase4-contact-consumer
        envFrom:
          - configMapRef:
              name: contactconsumer-env-config
          - secretRef:
              name: contact-secret
        ports:
        - containerPort: 6060
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "100Mi"
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-app
  annotations:
    description: "Deployment for rabbitmq"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-app
  template:
    metadata:
      labels:
        app: rabbitmq-app
    spec:
      containers:
      - name: rabbitmq-app
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15692
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-app
  annotations:
    description: "Deployment for prometheus"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-app
  template:
    metadata:
      labels:
        app: prometheus-app
    spec:
      containers:
      - name: prometheus-coll
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
            defaultMode: 420
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-app
  annotations:
    description: "Deployment for grafana"
spec:
  replicas: 1
  selector:
    matchLabels:
       app: grafana-app
  template:
    metadata:
     labels:
       app: grafana-app
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        # args:
        # - '--config=/grafana.ini'
        ports:
        - containerPort: 3000
        # securityContext:
        #   runAsUser: 0
        volumeMounts:
            - name: config-volume
              mountPath: /var/lib/grafana
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: grafana-pvc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  annotations:
    description: "Deployment for Redis"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---

## Services for Tech Challenge Phase 4
apiVersion: v1
kind: Service
metadata:
  name: sv-region-api
spec:
  type: NodePort
  selector:
    app: regionservice
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 8080
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: sv-contact-api
spec:
  type: NodePort
  selector:
    app: contactservice
  ports:
  - protocol: TCP
    port: 4040
    targetPort: 8080
    nodePort: 30071
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq-app
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30070
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: 15692
      nodePort: 30093
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ui
spec:
  type: NodePort
  selector:
    app: rabbitmq-app
  ports:
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30060
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: 15692
      nodePort: 30092

---
apiVersion: v1
kind: Service
metadata:
  name: sv-prometheus
spec:
  type: NodePort
  selector:
    app: prometheus-app
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30050
---
apiVersion: v1
kind: Service
metadata:
  name: sv-grafana
spec:
  type: NodePort
  selector:
    app: grafana-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30030

---

  apiVersion: v1
  kind: Service
  metadata:
    name: sqlserver
  spec:
    type: NodePort
    selector:
      app: sqlserver
    ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31433
---

apiVersion: v1
kind: Service
metadata:
  name: sv-redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30377


---
# Horizontal Pod Autoscalers
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: regionservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: regionservice
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: contactservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contactservice
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
