apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "fiap-prometheus-metrics-regions"
        metrics_path: /metrics
        static_configs:
          - targets: ["sv-region-api:5050"]
      - job_name: "fiap-prometheus-metrics-contacts"
        metrics_path: /metrics
        static_configs:
          - targets: ["sv-contact-api:4040"]
      - job_name: "fiap-prometheus-metrics-rabbitmq"
        metrics_path: /metrics
        static_configs:
          - targets: ["rabbitmq-service:15692"]
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-config
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
      - name: prometheus-metrics
      editable: true
      type: prometheus
      access: proxy
      url: sv-prometheus:9090
      isDefault: true
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: regionconsumer-env-config
data:
  MassTransit__QueueCreateRegion: region-insert-queue
  MassTransit__Server: rabbitmq-service
  ConnectionStrings__Cache: sv-redis:6379
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: contactconsumer-env-config
data:
  MassTransit__QueueCreateRegion: contact-insert-queue
  MassTransit__Server: rabbitmq-service
  ConnectionStrings__Cache: sv-redis:6379
  Integrations__RegionApiUrl: http://sv-region-api:5050/api
  MESSAGE: "Mensagem do ConfigMap ALTERADA NO YML!"
---