apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "fiap-prometheus-metrics-regions"
        metrics_path: /metrics
        static_configs:
          - targets: ["sv-region-api:5050"]
      - job_name: "fiap-prometheus-metrics-contacts"
        metrics_path: /metrics
        static_configs:
          - targets: ["sv-contact-api:4040"]
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-config
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
      - name: prometheus-metrics
      editable: true
      type: prometheus
      access: proxy
      url: sv-prometheus:9090
      isDefault: true